@echo off
echo Fixing DFX and PocketIC issues...

echo Stopping any running DFX processes...
dfx stop

echo Cleaning DFX cache...
if exist .dfx rmdir /s /q .dfx

echo Killing any processes on port 4943...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :4943') do taskkill /f /pid %%a 2>nul

echo Killing any processes on port 35245 (PocketIC)...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :35245') do taskkill /f /pid %%a 2>nul

echo Starting DFX with clean state...
dfx start --clean --background

echo Waiting for DFX to initialize...
timeout /t 10 /nobreak

echo Deploying canisters...
dfx deploy

echo Done! DFX should now be running properly.