name: Deploy WebSocket Server to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server/ws
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/dhaniverse-ws:latest
      
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dhaniverse-ws'
          images: ${{ secrets.ACR_LOGIN_SERVER }}/dhaniverse-ws:latest
      
      - name: Configure App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set --name dhaniverse-ws --resource-group dhaniverse-rg \
              --settings \
              DENO_ENV=production \
              JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}" \
              ALLOWED_ORIGINS="https://dhaniverse.vercel.app" \
              AUTH_SERVER_URL="https://api.dhaniverse.in" \
              PRODUCTION_AUTH_SERVER_URL="https://api.dhaniverse.in" \
              WEBSITES_PORT=8000
      
      - name: Configure WebSocket Support
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Enable WebSockets
            az webapp config set --name dhaniverse-ws --resource-group dhaniverse-rg --web-sockets-enabled true
            
            # Set always on to keep the app running
            az webapp config set --name dhaniverse-ws --resource-group dhaniverse-rg --always-on true